### ISSUE TITLE
3.0.0 release plan

### ISSUE THREAD

**Issue by sralloza** [sralloza/vcm#37]
## New features
* [x] Add link's name to notify database (#39)
* [x] Add `CHANGELOG`, where all changes are written down.
* [x] Add `check-updates` function. It will fetch the last version using the `VERSION` file of the `master` branch.
* [x] Add `check-updates` command. It will call `check-updates()`.
* [x] Add `max-logs` general setting to adjust max the number of log files that will be stored.
* [x] Use subject ids instead of urls in settings.
* [x] Add `exclude` command to exclude subjects ids.
* [x] Add `include` command to include subjects ids (remove id from exclude list).
* [x] Add command to handle setting section indexing.

## Bug fix
* [x] Fix TOML syntax in README (#36)
* [x] Fix example.png link in README (#35)
* [x] Improve exception messages

**Comment by sralloza** [comment]
This is a mayor release, because the handling of aliases is incompatible with the previous version.

**Comment by sralloza** [comment]
Released in 7f9f10c12289d4621f64d660d99af5bef5767a0c
